---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 

Five little girls, of Five, Four, Three, Two, One:  
Rolling on the hearthrug, full of tricks and fun.   

Five rosy girls, in years from Ten to Six:  
Sitting down to lessons - no more time for tricks.   

Five growing girls, from Fifteen to Eleven

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

What happens to a dream deferred?  

Does it dry up  
Like a raisin in the sun?  
Or fester like a sore—  
And then run?  
Does it stink like rotten meat?  
Or crust and sugar over—  
Like a syrupy sweet?  

Maybe it just sags  
Like a heavy load.  

Or does it explode?  
